config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'  
  resources :users, except: [:new, :show] do
    resources :keylists, only: [:show, :index, :destroy]
  end
  scope '/admin' do
    get 'generateKey', to: 'generatekeys#index'
    post 'generateKey', to: 'generatekeys#create'
    post 'dontgenerate', to: 'generatekeys#discard'
  end

  namespace :api, path: '/' do
    namespace :v1, path: '/' do
      scope '/word' do
        get ':word/definations', to: 'operations#definations'
        get ':word/examples', to: 'operations#examples'
        get ':word/relatedWords', to: 'operations#related_words'
      end
      scope '/words' do
        get 'randomWord', to: 'randomword#index'
      end
    end
  end

  match '*path', :to => 'application#routing_error', via: [:get, :post]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index #welcome page
  end
end

app/views/welcome/index.html.erb
<!-- Page Content -->
<section class="py-5">
<% if !logged_in? %>
  <div class="container" id="welcometext" >
    <h1>WordGame API Generator</h1>
    
    <p class="lead">Welcome to the WordGame API Generator. You can generate numerous APIs for your single account and use our API in your application for free!!</p>
    <h5> Click below to SignUp and Get started</h5>
    <%= link_to "Signup",signup_path,class:"btn btn-success btn-lg mt-2" %>
  </div>
<% else %>
  <div class="container" id="welcometext" >
    <h1>Welcome <%= current_user.firstname %> :)</h1>
    
    <p class="lead">Welcome to the WordGame API Generator. You can generate numerous APIs for your single account and use our API in your application for free!!</p>
    <h5> Click below to Check your API list or generate new API</h5>
    <p>
    <%= link_to "Check Your List",user_keylists_path(session[:user_id]),class:"btn btn-success btn-lg mt-2" %>
    <%= link_to "Generate new",generateKey_path(:email => current_user.email, :username => current_user.username, :password => session[:password]),class:"btn btn-success btn-lg mt-2" %>
    </p>
  </div>
  <%end%>