config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'  
  resources :users, except: [:new, :show] do
    resources :keylists, only: [:show, :index, :destroy]
  end
  scope '/admin' do
    get 'generateKey', to: 'generatekeys#index'
    post 'generateKey', to: 'generatekeys#create'
    post 'dontgenerate', to: 'generatekeys#discard'
  end

  namespace :api, path: '/' do
    namespace :v1, path: '/' do
      scope '/word' do
        get ':word/definations', to: 'operations#definations'
        get ':word/examples', to: 'operations#examples'
        get ':word/relatedWords', to: 'operations#related_words'
      end
      scope '/words' do
        get 'randomWord', to: 'randomword#index'
      end
    end
  end

  match '*path', :to => 'application#routing_error', via: [:get, :post]

end

app/controllers/generatekeys_controller.rb
class GeneratekeysController < ApplicationController
  before_action :require_login
    def index
      @val = {}
      @val[:email] = params[:email]
      @val[:username] = params[:username]
      pwd = params[:password]
      @user = User.find_by(username: @val[:username])
      puts @user
      if @user
        if @user.email == @val[:email] && @user.authenticate(pwd)
          @val[:API_KEY] = generate_api_key
          render 'match'
        else
          @word_dict = "User not found or wrong user data"
          render 'return_info/index'
        end
      else
        @word_dict = "User not found or wrong user data"
        render 'return_info/index'
      end
    end

    def create
#      byebug
      keyval = Keylist.new
      keyval.API_KEY = params[:api]
      keyval.count = 0
      keyval.user_id = params[:id]
      if keyval.save
        flash[:notice] = "saved"
        if session[:user_id] != nil
          redirect_to user_keylists_path(session[:user_id])
        else 
          @word_dict = "Key saved!!! login to continue"
          render 'return_info/index'
        end
      else
        flash.now[:alert] = "Something went wrong"
      end
    end

    def discard
      if session[:user_id] == nil
        @word_dict = "Key discarded. Please login to view your account"
        render 'return_info/index'
      else
        redirect_to user_keylists_path(session[:user_id])
      end
    end

    private   #generate api
    def generate_api_key
      SecureRandom.base58(200)
    end

end

app/views/generatekeys/match.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center sh adow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          By <%=@user.firstname%>
        </div>
        <div class="card-body">

          <h5 class="card-title"><%=link_to "API Key",class: "text-success"%></h5>          
          <p class="card-text"><%= @val[:API_KEY].to_s %></p>
          <%=link_to "Save", generateKey_path(request.params.merge(:api => @val[:API_KEY],:id => @user.id)), class: "btn btn-outline-success mr-2", method: :post %>
          <%=link_to "Discard", dontgenerate_path, class: "btn btn-outline-danger ml-2", method: :post, data: {confirm: "Are you sure?"} %>

        </div>
    </div>
  </div>
</div>