config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'  
  resources :users, except: [:new, :show] do
    resources :keylists, only: [:show, :index, :destroy]
  end
  scope '/admin' do
    get 'generateKey', to: 'generatekeys#index'
    post 'generateKey', to: 'generatekeys#create'
    post 'dontgenerate', to: 'generatekeys#discard'
  end

  namespace :api, path: '/' do
    namespace :v1, path: '/' do
      scope '/word' do
        get ':word/definations', to: 'operations#definations'
        get ':word/examples', to: 'operations#examples'
        get ':word/relatedWords', to: 'operations#related_words'
      end
      scope '/words' do
        get 'randomWord', to: 'randomword#index'
      end
    end
  end

  match '*path', :to => 'application#routing_error', via: [:get, :post]

end

app/models/concerns/keylist.rb
class Keylist < ApplicationRecord
  validates :API_KEY, presence: true, uniqueness: true, null: false
  validates :count, presence: true
  belongs_to :user
  has_many :api_categories
  has_many :categories, through: :api_categories
end

app/controllers/keylists_controller.rb
class KeylistsController < ApplicationController
  before_action :require_login
  def index
    @keylist=Keylist.where(:user_id => session[:user_id])
  end

  def destroy #delete a key
    #byebug
    keylist = Keylist.find(params[:id])
    keylist.destroy
    flash[:notice] = "successfully deleted"
    redirect_back(fallback_location: user_keylists_path(session[:user_id]))
  end

  def show #display a key
    @keylist = Keylist.find(params[:id])
  end

end

app/views/keylists/index.html.erb
<h1 class="text-center mt-4 rounded font-weight-lighter text-white">Keys Created By You</h1>

<div class="container">
<% @keylist.each_with_index do |keylist, index| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-2">
      <div class="card text-center shadow mb-3 bg-white rounded">
        <div class="card-header font-italic">
          By <%=keylist.user.firstname%>
        </div>

        <div class="card-body">

          <h5 class="card-title"><%=link_to "API Key "+(index+1).to_s, user_keylist_path(session[:user_id], keylist.id), class: "text-success"%></h5>
          <p class="card-text"><%=truncate(keylist.API_KEY, length: 10)+"..." %></p>
          <%=link_to "View", user_keylist_path(session[:user_id], keylist.id), class: "btn btn-outline-success"%>
          <%=link_to "Delete", user_keylist_path(session[:user_id], keylist.id), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
         <!-- <%=link_to "Copy", user_keylists_path(session[:user_id]), class: "btn btn-outline-info"%> -->

        </div>
        <div class="card-footer text-muted">
          <small>Used <%= keylist.count %> times</small><br/>
          <small>Created <%= time_ago_in_words(keylist.created_at) %> ago,
          Last Used <%= time_ago_in_words(keylist.updated_at) %> ago</small>
          
        </div>
      </div>
    </div>
  </div>
<%end%>
<div class="row justify-content-md-center">
  <div class="col-8 mb-5">
    <%= link_to "Generate API Key", generateKey_path(:email => session[:email], :username => session[:username], :password => session[:password]), class: "btn btn-outline-primary btn-block mt-2" %>
  </div>
</div>  
</div>

app/views/keylists/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          By <%=@keylist.user.firstname%>
        </div>
        <div class="card-body">

          <h5 class="card-title"><%=link_to "API Key",class: "text-success"%></h5>
          <p class="card-text"><%= @keylist.API_KEY %></p>
          <%=link_to "Back", user_keylists_path(session[:user_id]), class: "btn btn-outline-success"%>
          <%=link_to "Delete", user_keylist_path(session[:user_id], @keylist.id), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <!--<%=link_to "Copy", user_keylists_path(session[:user_id]), class: "btn btn-outline-info" %> -->
        </div>

        <div class="card-footer text-muted">
          <small>Used <%= @keylist.count %> times</small><br/>
          <small>Created <%= time_ago_in_words(@keylist.created_at) %> ago,
          Last Used <%= time_ago_in_words(@keylist.updated_at) %> ago</small>

      </div>
    </div>
  </div>
</div>