config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'  
  resources :users, except: [:new, :show] do
    resources :keylists, only: [:show, :index, :destroy]
  end
  scope '/admin' do
    get 'generateKey', to: 'generatekeys#index'
    post 'generateKey', to: 'generatekeys#create'
    post 'dontgenerate', to: 'generatekeys#discard'
  end

  namespace :api, path: '/' do
    namespace :v1, path: '/' do
      scope '/word' do
        get ':word/definations', to: 'operations#definations'
        get ':word/examples', to: 'operations#examples'
        get ':word/relatedWords', to: 'operations#related_words'
      end
      scope '/words' do
        get 'randomWord', to: 'randomword#index'
      end
    end
  end

  match '*path', :to => 'application#routing_error', via: [:get, :post]

end

app/views/layouts/_messages.html.erb
<% flash. each do |name, msg| %>
  <div class="alert alert-success" role="alert">
    <%=msg%>
 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "WordGame API Generator", root_path, class: "navbar-brand ml-5 pl-2", id: "logo"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mr-3">
        <li class="nav-item active" id="navelements">
        <%= link_to "Home", root_path, class:"nav-link text-light" %>
        </li>
        <li class="nav-item active" id="navelements">
        <%= link_to "About", root_path, class:"nav-link text-light" %>
        </li>
        <li class="nav-item active" id="navelements">
        <%= link_to "Services", root_path, class:"nav-link text-light" %>
        </li>

        <% if !logged_in? %>

        <li class="nav-item active" id="navelements">
          <%= link_to "Register", signup_path, class:"nav-link text-light" %>
        </li>

          <li class="nav-item active" id="navelements" >
            <%= link_to "Login", login_path, class:"nav-link text-light" %>
          </li>

        <% else %>
        <li class="nav-item active" id="navelements">
          <%= link_to "Generate", generateKey_path(:email => current_user.email, :username => current_user.username, :password => session[:password]), class:"nav-link text-light"%>
        </li>

        <li class="nav-item active" id="navelements">
          <%= link_to "Edit Profile", edit_user_path(current_user.id), class:"nav-link text-light"%>
        </li>

        <li class="nav-item active" id="navelements">
          <%= link_to "Logout", logout_path, class:"nav-link text-light", method: :delete, data: {confirm: "Do you want to Logout?"} %>
        </li>
        <% end %>
        <li class="nav-item active" id="navelements" >
          <%= link_to "Contact Us", root_path, class:"nav-link text-light" %>
        </li>

        <li class="nav-item active" id="navelements">
        <%= link_to "Generate key",generateKey_path(:email => session[:email], :username => session[:username], :password => session[:password]), class: "btn btn-outline-primary btn-block", id: "navbutton text-light" %>
        </li>
      </ul>
    </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordgameApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>